#!/bin/bash

##############################################################################
# genconfig (c) 2019 duncan brown (http://github.com/xovox/OpenArcadeDB
#
# This is an example script to generate RetroArch configs on a per-rom basis
# for CRT gaming.
##############################################################################

resolution="$(cat $1/monitor.resolution.vertical)"
rotation="$(cat $1/monitor.orientation)"
outputfile="$resolution.$rotation.cfg"

if [ ! -f "$outputfile" ]; then
{
cat << EOF
custom_viewport_width = "1920"
custom_viewport_height = "$resolution"
EOF

if [ "$rotation" = "V" ]; then
cat << EOF
video_allow_rotate = "true"
video_rotation = "1"
EOF
fi
} > $outputfile
fi

ln -s $outputfile $1.zip.cfg

exit

raidenk/game.cloneof:raiden
raidenk/game.controller:2
raidenk/game.genre:Shooter / Flying Vertical
raidenk/game.name:Raiden (Korea)
raidenk/game.players:2
raidenk/game.players.buttons:joy8way
raidenk/game.romof:raiden
raidenk/game.year:1990
raidenk/monitor.freq:59.6
raidenk/monitor.orientation:V
raidenk/monitor.resolution.horizontal:256
raidenk/monitor.resolution.vertical:224
raidenk/monitor.type:R

