#!/bin/bash

##############################################################################
#
# gentsv (c) 2019 duncan brown (http://github.com/xovox/OpenArcadeDB
#
# This is a simple script to demonstrate a single type of usefullness of the
# OpenArcadeDB.  It generates a .tsv file to stdout that's suitable for
# importing to many spreadsheet applications.
#
##############################################################################

columns="
game.name
game.name.short
game.publisher
game.year
game.genre
game.romof
game.bios
game.cloneof
game.coinslots
game.control.buttons
game.control.count
game.control.type
monitor.count
monitor.freq
monitor.orientation
monitor.ratio.horizontal
monitor.ratio.vertical
monitor.resolution.horizontal
monitor.resolution.vertical
monitor.type
"


# sqlite doesn't like dots in column names
sqlite_columns="$(sed 's/\./_/g' <<< "$columns")"

# column types for sqlite
declare -A sqlite_column_type="(
[game_rom]="text"
[game_name]="text"
[game_name_short]="text"
[game_publisher]="text"
[game_year]="int"
[game_genre]="text"
[game_romof]="text"
[game_bios]="text"
[game_cloneof]="text"
[game_coinslots]="int"
[game_control_buttons]="int"
[game_control_count]="int"
[game_control_type]="text"
[monitor_count]="int"
[monitor_freq]="real"
[monitor_orientation]="text"
[monitor_ratio_horizontal]="int"
[monitor_ratio_vertical]="int"
[monitor_resolution_horizontal]="int"
[monitor_resolution_vertical]="int"
[monitor_type]="text"
)"



geninfo() {
    echo -n "$game	"
    for field in $columns ; do
        echo -n "$(cat "$game/$field" 2> /dev/null)	"
    done
    echo
}

today=$(date +%Y%m%d)

tempdir=$(mktemp -d /dev/shm/OpenArcade-XXX)
targetdir=$PWD/OpenVGDB.$today
mkdir -pv $targetdir
clearline="$(tput el)"

gamecount="$(find arcade -mindepth 1 -maxdepth 1 | wc -l)"
gamenum=0
pushd arcade
for game in * ; do
    gamenum=$[ $gamenum + 1 ]
    echo -en "$clearline ($gamenum/$gamecount)	$game\r"
    geninfo > $tempdir/$game &
    while [ "$(jobs | wc -l)" -ge 100 ]; do
        sleep 1
    done
done

echo

echo "assembling arcade tsv base"

cat $tempdir/* \
    | sort \
    | sed 's/	$//' \
        > $targetdir/OpenArcadeDB_Linux.$today.tsv.tmp

echo "generating arcade db table"
{
    echo -n "create table arcade ("
    for column in game_rom $sqlite_columns ; do
        echo -n "$column ${sqlite_column_type[$column]}	"
    done | sed 's/	$//;s/	/, /g'
    echo ");"
cat << EOF
.separator "\t"
.import $targetdir/OpenArcadeDB_Linux.$today.tsv.tmp arcade
EOF
} | sqlite3 $targetdir/OpenVGDB.sqlite3

echo "assembling final tsv"
{
echo $game.rom $columns | sed 's/ /	/g'
cat $targetdir/OpenArcadeDB_Linux.$today.tsv.tmp 
} > $targetdir/OpenArcadeDB_Linux.$today.tsv

echo "generating line by line breakdown"
egrep -ris . * | sed 's/:/	/' | column -t -s'	' > $targetdir/OpenArcadeDB_Linux.$today.txt

# generating dos friendly versions
unix2dos < $targetdir/OpenArcadeDB_Linux.$today.tsv > $targetdir/OpenArcadeDB_DOS.$today.tsv
unix2dos < $targetdir/OpenArcadeDB_Linux.$today.txt > $targetdir/OpenArcadeDB_DOS.$today.txt
popd

rm -fv $targetdir/*tmp

echo "Obtained from https://github.com/xovox/OpenArcadeDB" > $targetdir/README.txt

exit
