#!/bin/bash

##############################################################################
# genRetroCRT (c) 2019 duncan brown (http://github.com/xovox/OpenArcadeDB
#
# This is an example script to generate RetroArch configs & links for hdmi
# timingson a per-rom basis # for CRT gaming.  This is a very rough work in
# progress.
#
# See https://github.com/xovox/RetroCRT
##############################################################################

outdir=/tmp/roms

mkdir -pv $outdir

genconfig(){
	echo "custom_viewport_width = \"1920\""
	echo "custom_viewport_height = \"$vertical\""

	if [ "$rotation" = "V" ]; then
		echo "video_allow_rotate = \"true\""
		echo "video_rotation = \"{{ rotate_ra }}\""
	fi

	if [ "$vertical" -gt 232 ] && [ "$vertical" -le "256" ]; then
		echo "custom_viewport_y = \"-$[ ($vertical - 232) / 2 ]\""
	fi
} 

for game in * ; do
	echo -n "$game "
	if [ -f "$game/monitor.resolution.vertical" ]; then
		export vertical="$(cat $game/monitor.resolution.vertical)"
		export horizontal="$(cat $game/monitor.resolution.horizontal)"
		export rotation="$(cat $game/monitor.orientation)"
		if [ "$vertical" -le 256 ]; then
			if [ ! -f $outdir/$vertical.$rotation.cfg ]; then
				genconfig > $outdir/$vertical.$rotation.cfg
			fi
	
			echo ln -sfv $vertical.$rotation.cfg $game.zip.cfg >> /tmp/genromlinks
			echo ln -sfv ../1920_$vertical $game >> /tmp/gentimings
		fi
	fi
done

chmod +x /tmp/gen{timings,romlinks}
