#!/bin/bash

##############################################################################
#
# gentsv (c) 2019 duncan brown (http://github.com/xovox/OpenArcadeDB
#
# This is a simple script to demonstrate a single type of usefullness of the
# OpenArcadeDB.  It generates a .tsv file to stdout that's suitable for
# importing to many spreadsheet applications.
#
##############################################################################

columns="
game.name
game.publisher
game.year
game.genre
game.romof
game.bios
game.cloneof
game.coinslots
game.control.buttons
game.control.count
game.control.type
monitor.count
monitor.freq
monitor.orientation
monitor.ratio.horizontal
monitor.ratio.vertical
monitor.resolution.horizontal
monitor.resolution.vertical
monitor.type
"

echo game.rom $columns | sed 's/ /	/g'
for game in * ; do
	echo -n "$game	"
	for field in $columns ; do
		echo -n "$(cat "$game/$field" 2> /dev/null)	"
	done
	echo
done

exit
