#!/bin/bash

##############################################################################
#
# gentsv (c) 2019 duncan brown (http://github.com/xovox/OpenGamesDB
#
# This is a simple script to demonstrate a single type of usefullness of the
# OpenGamesDB.  It generates a .tsv file to stdout that's suitable for
# importing to many spreadsheet applications.
#
##############################################################################

fields="
game.cloneof
game.romof
game.name
game.year
game.genre
game.coinslots
game.control.buttons
game.control.count
game.controller
game.control.type
monitor.freq
monitor.type
monitor.orientation
monitor.ratio.horizontal
monitor.ratio.vertical
monitor.resolution.horizontal
monitor.resolution.vertical
"

echo game.rom $fields | sed 's/ /	/g'
for game in * ; do
	echo -n "$game	"
	for field in $fields ; do
		echo -n "$(cat "$game/$field" 2> /dev/null)	"
	done
	echo
done

exit
